name: emo_book_flutter
description: Book suggestion service with User Emotion
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # frameworks
  get: ^4.3.6

  # Utils
  freezed_annotation:
  google_sign_in: ^5.0.7
  responsive_builder: ^0.4.1
  url_launcher: ^6.0.4
  # UIs
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  flutter_signin_button: ^2.0.0

  # Firebase
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.3


  # Custom library
  easy_web_view:
    git: https://github.com/KKimj/easy_web_view
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true

  fonts:
    - family : NanumSquareRound
      fonts:
      - asset : assets/fonts/NanumSquareRoundL.ttf
        weight : 300
      - asset : assets/fonts/NanumSquareRoundR.ttf
        weight : 400
      - asset : assets/fonts/NanumSquareRoundB.ttf
        weight : 700
      - asset : assets/fonts/NanumSquareRoundEB.ttf
        weight : 800
      
