name: emo_book_flutter
description: Book suggestion service with User Emotion
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # frameworks
  get: ^4.3.6

  # Utils
  books_finder:
    git: 
      url: https://github.com/KKimj/books_finder
      ref: 8da541210e9bd8a8c2b5cfd7431e54648ce74176
  freezed_annotation:
  google_sign_in: ^5.0.7
  http: ^0.13.4
  responsive_builder: ^0.4.1
  url_launcher: ^6.0.4
  
  # UIs
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  flutter_signin_button: ^2.0.0

  # Firebase
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "web/icons/ms-icon-310x310.png"

flutter:
  uses-material-design: true

  fonts:
    - family : NanumSquareRound
      fonts:
      - asset : assets/fonts/NanumSquareRoundL.ttf
        weight : 300
      - asset : assets/fonts/NanumSquareRoundR.ttf
        weight : 400
      - asset : assets/fonts/NanumSquareRoundB.ttf
        weight : 700
      - asset : assets/fonts/NanumSquareRoundEB.ttf
        weight : 800
      
