name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# https://github.com/dart-lang/setup-dart/blob/main/README.md
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev]
    env:
      working-directory: emo_book_flutter
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ env.working-directory }}
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze
        working-directory: ${{ env.working-directory }}
      - name: Run tests
        run: dart test
        working-directory: ${{ env.working-directory }}
