name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# https://github.com/subosito/flutter-action/blob/master/README.md
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev]
    env:
      working-directory: ./emo_book_flutter
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: ${{ matrix.sdk }}
      
      - run: dart --version
        working-directory: ${{ env.working-directory }}
      - run: flutter --version
        working-directory: ${{ env.working-directory }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.working-directory }}
        
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze project source
        run: dart analyze --fatal-infos
        working-directory: ${{ env.working-directory }}
        
      - name: Run tests
        run: flutter test
        working-directory: ${{ env.working-directory }}
